// Code generated by go-swagger; DO NOT EDIT.

package streams

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/matoous/sportstats/integrations/strava/models"
)

// GetRouteStreamsReader is a Reader for the GetRouteStreams structure.
type GetRouteStreamsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRouteStreamsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetRouteStreamsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetRouteStreamsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetRouteStreamsOK creates a GetRouteStreamsOK with default headers values
func NewGetRouteStreamsOK() *GetRouteStreamsOK {
	return &GetRouteStreamsOK{}
}

/* GetRouteStreamsOK describes a response with status code 200, with default header values.

The set of requested streams.
*/
type GetRouteStreamsOK struct {
	Payload *models.StreamSet
}

func (o *GetRouteStreamsOK) Error() string {
	return fmt.Sprintf("[GET /routes/{id}/streams][%d] getRouteStreamsOK  %+v", 200, o.Payload)
}
func (o *GetRouteStreamsOK) GetPayload() *models.StreamSet {
	return o.Payload
}

func (o *GetRouteStreamsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StreamSet)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRouteStreamsDefault creates a GetRouteStreamsDefault with default headers values
func NewGetRouteStreamsDefault(code int) *GetRouteStreamsDefault {
	return &GetRouteStreamsDefault{
		_statusCode: code,
	}
}

/* GetRouteStreamsDefault describes a response with status code -1, with default header values.

Unexpected error.
*/
type GetRouteStreamsDefault struct {
	_statusCode int

	Payload *models.Fault
}

// Code gets the status code for the get route streams default response
func (o *GetRouteStreamsDefault) Code() int {
	return o._statusCode
}

func (o *GetRouteStreamsDefault) Error() string {
	return fmt.Sprintf("[GET /routes/{id}/streams][%d] getRouteStreams default  %+v", o._statusCode, o.Payload)
}
func (o *GetRouteStreamsDefault) GetPayload() *models.Fault {
	return o.Payload
}

func (o *GetRouteStreamsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Fault)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
