// Code generated by go-swagger; DO NOT EDIT.

package running_races

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new running races API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for running races API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	GetRunningRaceByID(params *GetRunningRaceByIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetRunningRaceByIDOK, error)

	GetRunningRaces(params *GetRunningRacesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetRunningRacesOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  GetRunningRaceByID gets running race

  Returns a running race for a given identifier.
*/
func (a *Client) GetRunningRaceByID(params *GetRunningRaceByIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetRunningRaceByIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetRunningRaceByIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "getRunningRaceById",
		Method:             "GET",
		PathPattern:        "/running_races/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetRunningRaceByIDReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetRunningRaceByIDOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*GetRunningRaceByIDDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  GetRunningRaces lists running races

  Returns a list running races based on a set of search criteria.
*/
func (a *Client) GetRunningRaces(params *GetRunningRacesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetRunningRacesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetRunningRacesParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "getRunningRaces",
		Method:             "GET",
		PathPattern:        "/running_races",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetRunningRacesReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetRunningRacesOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*GetRunningRacesDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
